\version "2.18.2"
\language "english"

\include "notes/one.ily"
\include "notes/two.ily"
\include "notes/three.ily"
\include "notes/four.ily"
\include "notes/five.ily"
\include "notes/six.ily"
\include "notes/seven.ily"
\include "notes/eight.ily"
\include "notes/nine.ily"
\include "notes/ten.ily"
\include "notes/eleven.ily"
\include "notes/twelve.ily"
